---
title: "rispacs_make_rds"
author: "Mirza Hasanbasic"
date: "07/01/2020"
output:
  html_document:
    toc: true
    theme: united
knit: (function(inputFile, encoding) { 
      out_dir <- '../docs';
      rmarkdown::render(inputFile,
                        encoding=encoding, 
                        output_file=file.path(dirname(inputFile), out_dir, 'rispacs_make_rds.html')) })
---


# Program name

The program name is `rispacs_make_rds.R` which can be located in the scripts folder.

# Project File

The project file is currently `Hvidovre-new`. You should open the `R Project` icon named `Hvidovre`

# Purpose

The purpose of this file is to extract the information of each subspecility and put it into its own folder as an `activity.rds`.
The output can be found in `Hvidovre-new/data/processed/FBE/rispacs` and then the folders `CT`, `gennemlyser`, 
`MR`, `PET`, `RTG`, `UL`, and `XRU` have their own `activity.rds` file.

# Comments



# Data Used

The data used can be found in `data/processed/FBE/rispacs` where the following files are used:

* `pacs_data_afgr.rds`
* `ris_data_afgr.rds`
* `sks_beskrivelser.rds`

You can use `readRDS()` to read these files.

The raw data can be found in `Server = "RGHPRODAPP007\\RGHPRODAPP007"` for the `ris` and `pacs`.  While for the `sks_beskrivelser` this data is located in `Server = "RGHPRODAPP006\\RGHPRODAPP006"`.

The `r` code can be found below.

```
Analyse <- dbConnect(odbc::odbc(),
                     Driver = "SQL server",
                     Server = "RGHPRODAPP007\\RGHPRODAPP007",
                     Database = "Analyse",
                     encoding = "latin1")

RIS_HVIDOVRE <- tbl(Analyse, in_schema("FBE", "RIS_HVIDOVRE_AFGR")) %>%
    collect()

PACS_HVIDOVRE <- tbl(Analyse, in_schema("FBE", "PACS_HVIDOVRE_AFGR")) %>%
    collect()
 
pacs_data <- PACS_HVIDOVRE
ris_data <- RIS_HVIDOVRE

dbDisconnect(Analyse) 
```

and 

```
Analyse_sks <- dbConnect(odbc::odbc(),
                     Driver = "SQL server",
                     Server = "RGHPRODAPP006\\RGHPRODAPP006",
                     Database = "DB_Report",
                     encoding = "latin1")


sks_data <- tbl(Analyse_sks, in_schema("DATA", "V_SKS_KODER")) %>%
    collect()

dbDisconnect(Analyse_sks) 
```

# Contents

A loop runs for all the machines that are available. For each machine there is a condition that tells when two `accession numbers` can merge. To merge `dog_combine_accession_numbers()` and `dog_spread_SKS()` are used. Furthermore some small additions are made to each dataframe, such as adding quarters and using the lubridate to add new columns with year, day, date, etc.

# Updates




